version: '3'
services:
  node:
    env_file: docker/production/.envLogia
    build:
      context: .
      dockerfile: docker/production/node/Dockerfile
      args:
        NODE_VERSION: "16"
        UID: 1000
        GID: 1000
    volumes:
      - .:/app
    command: sh -c "node index.js"
  concurrency:
    build:
      context: .
      dockerfile: concurrency/Dockerfile
    ports:
      - "7007:7007"
    volumes:
      - .:/code